-- INSERT INTO my_user (username, password, email,phone,role) values ('hashem', '123', 'hash@gmail.com', '0535862396', 'customer');
--
--
-- INSERT INTO customer (first_name, last_name, age,gender, my_user_id) values ('hashem', 'bajabaa', 20, 'male', 1);
-- -- INSERT INTO customer (first_name, last_name, age,gender, my_user_id) values ('ali', 'bajabaa', 20, 'male', 2);
-- -- INSERT INTO customer (first_name, last_name, age,gender, my_user_id) values ('aziz', 'bajabaa', 20, 'male', 3);
-- -- INSERT INTO customer (first_name, last_name, age,gender, my_user_id) values ('moe', 'bajabaa', 20, 'male', 4);